FROM go-build:latest AS builder

COPY . .
RUN go mod download
RUN go generate ./services/...
RUN go build -o ./backend -tags=integration ./tests/integration/mock/backend

FROM golang:1.22.4-alpine3.20 AS service
COPY --from=builder /app/backend .

# # Ensure the binary is executable
RUN chmod +x backend

ENTRYPOINT ["./backend"]

