FROM go-build:latest AS builder

COPY . .
RUN go mod download
RUN go generate ./services/...
# save results to test_results which forces caching of the test results. 
# this avoids testing again on each build without changes
RUN go test -coverprofile=coverage.out ./... && go tool cover -html=coverage.out -o coverage.html
RUN go build -o ./balance

