FROM balance-build:latest as builder

FROM golang:1.22.4-alpine3.20 as service
COPY --from=builder /app/balance .

# Ensure the binary is executable
RUN chmod +x balance

# debug tools
# RUN apk update && apk add busybox-extras

ENTRYPOINT ["./balance"]

